export const countryData = {
  USA: [
    "New York",
    "California",
    "Texas",
    "Florida",
    "Illinois",
    "Pennsylvania",
    "Ohio",
    "Georgia",
    "North Carolina",
    "Michigan",
  ],
  Canada: [
    "Ontario",
    "Quebec",
    "British Columbia",
    "Alberta",
    "Manitoba",
    "Saskatchewan",
    "Nova Scotia",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Prince Edward Island",
  ],
  Nigeria: [
    "Lagos",
    "Abuja",
    "Rivers",
    "Kano",
    "Oyo",
    "Kaduna",
    "Plateau",
    "Delta",
    "Imo",
    "Enugu",
  ],
  "South Africa": [
    "Gauteng",
    "Western Cape",
    "KwaZulu-Natal",
    "Eastern Cape",
    "Free State",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
  ],
  France: [
    "Île-de-France",
    "Provence-Alpes-Côte d'Azur",
    "Auvergne-Rhône-Alpes",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Grand Est",
    "Brittany",
    "Normandy",
    "Pays de la Loire",
    "Centre-Val de Loire",
  ],
  Germany: [
    "Bavaria",
    "Berlin",
    "North Rhine-Westphalia",
    "Baden-Württemberg",
    "Lower Saxony",
    "Hesse",
    "Saxony",
    "Rhineland-Palatinate",
    "Thuringia",
    "Saxony-Anhalt",
  ],
  Australia: [
    "New South Wales",
    "Quebec",
    "Victoria",
    "Queensland",
    "Western Australia",
    "South Australia",
    "Tasmania",
    "Northern Territory",
    "Australian Capital Territory",
  ],
  India: [
    "Maharashtra",
    "Tamil Nadu",
    "Uttar Pradesh",
    "Karnataka",
    "Gujarat",
    "West Bengal",
    "Rajasthan",
    "Andhra Pradesh",
    "Madhya Pradesh",
    "Kerala",
  ],
  UK: ["England", "Scotland", "Wales", "Northern Ireland"],
  Japan: [
    "Tokyo",
    "Kanagawa",
    "Osaka",
    "Aichi",
    "Saitama",
    "Chiba",
    "Hyogo",
    "Fukuoka",
    "Hokkaido",
    "Shizuoka",
  ],
  Italy: [
    "Lombardy",
    "Lazio",
    "Sicily",
    "Veneto",
    "Emilia-Romagna",
    "Piedmont",
    "Tuscany",
    "Apulia",
    "Campania",
    "Calabria",
  ],
  Spain: [
    "Catalonia",
    "Madrid",
    "Andalusia",
    "Valencian Community",
    "Galicia",
    "Castile and León",
    "Basque Country",
    "Castilla-La Mancha",
    "Asturias",
    "Aragon",
  ],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Minas Gerais",
    "Bahia",
    "Paraná",
    "Rio Grande do Sul",
    "Pernambuco",
    "Ceará",
    "Pará",
    "Santa Catarina",
  ],
  Mexico: [
    "Mexico City",
    "Jalisco",
    "Nuevo León",
    "Veracruz",
    "Puebla",
    "Guanajuato",
    "Chiapas",
    "Michoacán",
    "Oaxaca",
    "Chihuahua",
  ],
  China: [
    "Guangdong",
    "Jiangsu",
    "Shandong",
    "Zhejiang",
    "Henan",
    "Sichuan",
    "Hunan",
    "Anhui",
    "Hebei",
    "Hubei",
  ],
};

export const cityData = {
  "New York": ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany"],
  California: [
    "Los Angeles",
    "San Francisco",
    "San Diego",
    "San Jose",
    "Sacramento",
  ],
  Texas: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"],
  Florida: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg"],
  Ontario: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton"],
  Quebec: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"],
  Lagos: ["Lagos", "Ikeja", "Badagry", "Epe", "Ikorodu"],
  "Western Cape": ["Cape Town", "Stellenbosch", "George", "Paarl", "Worcester"],
  "Île-de-France": [
    "Paris",
    "Boulogne-Billancourt",
    "Montreuil",
    "Saint-Denis",
    "Argenteuil",
  ],
  Bavaria: ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Ingolstadt"],
  "New South Wales": [
    "Sydney",
    "Newcastle",
    "Wollongong",
    "Albury",
    "Tamworth",
  ],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik"],
  England: ["London", "Birmingham", "Manchester", "Leeds", "Liverpool"],
  Tokyo: ["Shinjuku", "Shibuya", "Minato", "Chiyoda", "Taito"],
  Lombardy: ["Milan", "Bergamo", "Brescia", "Como", "Varese"],
  Catalonia: ["Barcelona", "Girona", "Lleida", "Tarragona", "Badalona"],
  "São Paulo": [
    "São Paulo",
    "Campinas",
    "Santos",
    "Sorocaba",
    "São José dos Campos",
  ],
  "Mexico City": [
    "Mexico City",
    "Coyoacán",
    "Tlalpan",
    "Iztapalapa",
    "Azcapotzalco",
  ],
  Guangdong: ["Guangzhou", "Shenzhen", "Foshan", "Dongguan", "Zhuhai"],
  // Note: This pattern should be extended to cover all states/regions listed in `countryData`.
};
