export const tableData = [
    {
      room: "101",
      item: "Chair",
      frequency: 7,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "102",
      item: "Table",
      frequency: 9,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "103",
      item: "Desk",
      frequency: 3,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "104",
      item: "PC",
      frequency: 3,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "105",
      item: "Screens",
      frequency: 23,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "106",
      item: "Chair",
      frequency: 6,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "107",
      item: "Chair",
      frequency: 9,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
    {
      room: "108",
      item: "Chair",
      frequency: 8,
      lastCleaned: "2024-03-15",
      nextDue: "2024-03-22",
      pastDue: "No",
      assignedTo: "John Doe",
      itemStatus: "Good",
      workOrderId: "W1234",
      evidenceLink: "https://google.com",
    },
  ];